services:
  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

  app:
    build:
      context: ./app
      args:
        http_proxy: http://proxymg.prodemge.gov.br:8080
        https_proxy: http://proxymg.prodemge.gov.br:8080
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"     # ⬅️ Agora acessível via IP:8000
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - http_proxy=http://proxymg.prodemge.gov.br:8080
      - https_proxy=http://proxymg.prodemge.gov.br:8080
    networks:
      - app_network

networks:
  app_network:

volumes:
  redis_data:

